#ifndef _MEM_C_
#define _MEM_C_
void *memcpy(void *dst,void *src,unsigned long int size)
{
	asm "push %rcx"
	asm "push %rdx"
	asm "push %rbx"
	asm "push %rsi"
	asm "push %rdi"
	asm "push %r8"
	asm "push %r9"
	asm "push %r10"
	asm "push %r11"
	asm "push %r12"
	asm "mov 16(%rbp),%rax"
	asm "mov 24(%rbp),%rdx"
	asm "mov 32(%rbp),%rcx"
	asm "cmp $8,%rcx"
	asm "jb @_memcpy_X33"
	asm "test $1,%dl"
	asm "je @_memcpy_X11"
	asm "mov (%rdx),%bl"
	asm "mov %bl,(%rax)"
	asm "inc %rax"
	asm "inc %rdx"
	asm "dec %rcx"
	asm "@_memcpy_X11"
	asm "test $2,%dl"
	asm "je @_memcpy_X12"
	asm "mov (%rdx),%bx"
	asm "mov %bx,(%rax)"
	asm "add $2,%rax"
	asm "add $2,%rdx"
	asm "sub $2,%rcx"
	asm "@_memcpy_X12"
	asm "test $4,%dl"
	asm "je @_memcpy_X13"
	asm "mov (%rdx),%ebx"
	asm "mov %ebx,(%rax)"
	asm "add $4,%rax"
	asm "add $4,%rdx"
	asm "sub $4,%rcx"
	asm "@_memcpy_X13"
	asm "sub $64,%rcx"
	asm "jb @_memcpy_X21"
	asm "@_memcpy_X22"
	asm "mov (%rdx),%rbx"
	asm "mov 8(%rdx),%rsi"
	asm "mov 16(%rdx),%rdi"
	asm "mov 24(%rdx),%r8"
	asm "mov 32(%rdx),%r9"
	asm "mov 40(%rdx),%r10"
	asm "mov 48(%rdx),%r11"
	asm "mov 56(%rdx),%r12"
	asm "mov %rbx,(%rax)"
	asm "mov %rsi,8(%rax)"
	asm "mov %rdi,16(%rax)"
	asm "mov %r8,24(%rax)"
	asm "mov %r9,32(%rax)"
	asm "mov %r10,40(%rax)"
	asm "mov %r11,48(%rax)"
	asm "mov %r12,56(%rax)"
	asm "add $64,%rax"
	asm "add $64,%rdx"
	asm "sub $64,%rcx"
	asm "jae @_memcpy_X22"
	asm "@_memcpy_X21"
	asm "test $32,%cl"
	asm "je @_memcpy_X31"
	asm "mov (%rdx),%rbx"
	asm "mov 8(%rdx),%rsi"
	asm "mov 16(%rdx),%rdi"
	asm "mov 24(%rdx),%r8"
	asm "mov %rbx,(%rax)"
	asm "mov %rsi,8(%rax)"
	asm "mov %rdi,16(%rax)"
	asm "mov %r8,24(%rax)"
	asm "add $32,%rax"
	asm "add $32,%rdx"
	asm "@_memcpy_X31"
	asm "test $16,%cl"
	asm "je @_memcpy_X32"
	asm "mov (%rdx),%rbx"
	asm "mov 8(%rdx),%rsi"
	asm "mov %rbx,(%rax)"
	asm "mov %rsi,8(%rax)"
	asm "add $16,%rax"
	asm "add $16,%rdx"
	asm "@_memcpy_X32"
	asm "test $8,%cl"
	asm "je @_memcpy_X33"
	asm "mov (%rdx),%rbx"
	asm "mov %rbx,(%rax)"
	asm "add $8,%rax"
	asm "add $8,%rdx"
	asm "@_memcpy_X33"
	asm "test $4,%cl"
	asm "je @_memcpy_X34"
	asm "mov (%rdx),%ebx"
	asm "mov %ebx,(%rax)"
	asm "add $4,%rax"
	asm "add $4,%rdx"
	asm "@_memcpy_X34"
	asm "test $2,%cl"
	asm "je @_memcpy_X35"
	asm "mov (%rdx),%bx"
	asm "mov %bx,(%rax)"
	asm "add $2,%rax"
	asm "add $2,%rdx"
	asm "@_memcpy_X35"
	asm "test $1,%cl"
	asm "je @_memcpy_X36"
	asm "mov (%rdx),%bl"
	asm "mov %bl,(%rax)"
	asm "@_memcpy_X36"
	asm "pop %r12"
	asm "pop %r11"
	asm "pop %r10"
	asm "pop %r9"
	asm "pop %r8"
	asm "pop %rdi"
	asm "pop %rsi"
	asm "pop %rbx"
	asm "pop %rdx"
	asm "pop %rcx"
	asm "mov 16(%rbp),%rax"
}
void *memset(void *mem,int val,unsigned long int size)
{
	asm "push %rcx"
	asm "push %rdx"
	asm "movzbl 24(%rbp),%edx"
	asm "mov $0x101010101010101,%rax"
	asm "mul %rdx"
	asm "mov %rax,%rdx"
	asm "mov 16(%rbp),%rax"
	asm "mov 32(%rbp),%rcx"
	asm "cmp $8,%rcx"
	asm "jb @_memset_X33"
	asm "test $1,%al"
	asm "je @_memset_X11"
	asm "mov %dl,(%rax)"
	asm "inc %rax"
	asm "dec %rcx"
	asm "@_memset_X11"
	asm "test $2,%al"
	asm "je @_memset_X12"
	asm "mov %dx,(%rax)"
	asm "add $2,%rax"
	asm "sub $2,%rcx"
	asm "@_memset_X12"
	asm "test $4,%al"
	asm "je @_memset_X13"
	asm "mov %edx,(%rax)"
	asm "add $4,%rax"
	asm "sub $4,%rcx"
	asm "@_memset_X13"
	asm "sub $64,%rcx"
	asm "jb @_memset_X21"
	asm "@_memset_X22"
	asm "mov %rdx,(%rax)"
	asm "mov %rdx,8(%rax)"
	asm "mov %rdx,16(%rax)"
	asm "mov %rdx,24(%rax)"
	asm "mov %rdx,32(%rax)"
	asm "mov %rdx,40(%rax)"
	asm "mov %rdx,48(%rax)"
	asm "mov %rdx,56(%rax)"
	asm "add $64,%rax"
	asm "sub $64,%rcx"
	asm "jae @_memset_X22"
	asm "@_memset_X21"
	asm "test $32,%cl"
	asm "je @_memset_X31"
	asm "mov %rdx,(%rax)"
	asm "mov %rdx,8(%rax)"
	asm "mov %rdx,16(%rax)"
	asm "mov %rdx,24(%rax)"
	asm "add $32,%rax"
	asm "@_memset_X31"
	asm "test $16,%cl"
	asm "je @_memset_X32"
	asm "mov %rdx,(%rax)"
	asm "mov %rdx,8(%rax)"
	asm "add $16,%rax"
	asm "@_memset_X32"
	asm "test $8,%cl"
	asm "je @_memset_X33"
	asm "mov %rdx,(%rax)"
	asm "add $8,%rax"
	asm "@_memset_X33"
	asm "test $4,%cl"
	asm "je @_memset_X34"
	asm "mov %edx,(%rax)"
	asm "add $4,%rax"
	asm "@_memset_X34"
	asm "test $2,%cl"
	asm "je @_memset_X35"
	asm "mov %dx,(%rax)"
	asm "add $2,%rax"
	asm "@_memset_X35"
	asm "test $1,%cl"
	asm "je @_memset_X36"
	asm "mov %dl,(%rax)"
	asm "@_memset_X36"
	asm "pop %rdx"
	asm "pop %rcx"
	asm "mov 16(%rbp),%rax"
}
#endif
